---
name: 'Format'
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.AUTOMATION_PAT }}
      - name: 'Setup'
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.1.5
      - name: 'Format'
        id: fmt
        run: terraform fmt -recursive
      - name: 'Fix'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'terraform fmt: automated action'
